<?php
/**
 * Created by PhpStorm.
 * User: finley
 * Date: 14-06-16
 * Time: 22:11
 */

namespace App\Controller\Ajax;

use App\Controller\AppController;
use Cake\Network\Exception\MethodNotAllowedException;

class ActivitiesController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadComponent('RequestHandler');
    }

    public function index() {
        if($this->request->isAjax() || 1==1) {
            $activities = $this->Activities->find('all', ['contain' => ['Users' => ['PrimaryRole']]])->limit(10);
            
            $this->set(compact('activities'));
            $this->set('_serialize', ['activities']);
        }
        else
        {
            throw new MethodNotAllowedException("AJAX request only");
        }
    }
}