<?php
/**
 * Created by PhpStorm.
 * User: finley
 * Date: 14-06-16
 * Time: 01:07
 */

namespace App\Controller\Ajax;


use App\Controller\AppController;
use Cake\Network\Exception\MethodNotAllowedException;
use Cake\Network\Exception\NotFoundException;

class ChatsController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadComponent('RequestHandler');
    }

    public function index() {
        if($this->request->isAjax()) {
            $chats = $this->Chats->find('all')->contain(['Users' => ['PrimaryRole']])->limit(25);

            $this->set(compact('chats'));
            $this->set('_serialize', ['chats']);
        }
        else
        {
            throw new MethodNotAllowedException("AJAX request only");
        }
    }

    public function lastchat($id) {
        if($this->request->isAjax()) {
            $chat = $this->Chats->get($id);

            if(is_null($chat)) {
                throw new NotFoundException("Last chat not found!");
            }

            $this->set(compact('chats'));
            $this->set('_serialize', ['chats']);

        }
        else
        {
            throw new MethodNotAllowedException("AJAX request only");
        }
    }
}